// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgnaltmjvwyahimumbqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnbmFsdG1qdnd5YWhpbXVtYnF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjExNDIsImV4cCI6MjA2MDk5NzE0Mn0.ExP1EH-QxqxmerfnOzPqzyOyOgdjuyJ2cSwkV1gA7PY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);